using ProblemSolveConsole.AdventofCode;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProblemSolveConsoleUnitTest.AdventofCode
{
    public class _2024D8Test
    {
        private _2024D8 _2024D8;
        public _2024D8Test()
        {
            _2024D8 = new _2024D8();
        }
        [Fact]
        public void GetAntinodeSumTest()
        {
            var result = _2024D8.GetAntinodeSum(@"............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............");
            Assert.Equal(14, result);
        }
        [Fact]
        public void GetAntinodeSum2Test()
        {
            var result = _2024D8.GetAntinodeSum2(@"............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............");
            Assert.Equal(34, result);
        }
    }
}
